### PR TITLE
Refresh sub result

### LINKED ISSUE #432: Errors in the submission of tasks
There are a number of errors in the submission of tasks:

- [x] If a text (Type Text) was submitted, the request fails with a 404 error:
grafik
- [x] If something is submitted, the result is requested too early, so the new results are not displayed
- [x] The Checker configuration does not have a return button.

### LINKED ISSUE #442: Error while deleting
- [ ] If you try to delete a course nothing happens
- [x] If you try to delete a task that you have passed, the following error will occur:
grafik
- [x] If you try to delete a (Runner- ) configuration from a task you have passed the following error will occur:
grafik

### LINKED ISSUE #479: automatic refreshing of submission page after a result is due
Currently users have to refresh the webbrowser to see the results of their query. Also the resubmit button is contra intuitive as the users think it will seek for the result of their submission.

### PR DESCRIPTION
**Pull request by andrej-sajenko**
For a change list see commits.

Fixes #479
Fixes #442 
Fixes #432

### CODE REVIEW

File: web-gui/src/app/page-components/task-detail/task-detail.component.ts [hunk 1]
```diff
@@ -71,6 +72,7 @@ export class TaskDetailComponent implements OnInit {
         if (submissions.length == 0) {
           this.status = <boolean>null
         } else {
+          this.pending = submissions.reverse()[0].results?.length == 0
```
Comment (mxsph) [inline web-gui/src/app/page-components/task-detail/task-detail.component.ts:75]: Since the existing list is reversed here, the submissions are displayed incorrectly.

**Review by mxsph — CHANGES_REQUESTED** [review]
Updating the solution works, but the loading circle is not displayed while waiting for the submission result (it is only displayed when you exit and reopen the task).

**Review by hwng38 — COMMENTED** [review]
Is the result table supposed to be missing?

File: web-gui/src/app/page-components/task-detail/task-detail.component.ts (hunk 1 above)
Comment (andrej-sajenko) [reply web-gui/src/app/page-components/task-detail/task-detail.component.ts:75]: Hmm, I think I got used to have immutable states. Should just use `submissions[submissions.length - 1]` to access the last element.

However, am I right with the assumption that a submission is "pending" if the results array of a submission is empty?

**Comment by andrej-sajenko** [comment]
> Is the result table supposed to be missing?

No, I think not.

File: web-gui/src/app/page-components/task-detail/task-detail.component.ts (hunk 1 above)
Comment (mxsph) [reply web-gui/src/app/page-components/task-detail/task-detail.component.ts:75]: Yes, your assumption is correct.

Comment (andrej-sajenko) [reply web-gui/src/app/page-components/task-detail/task-detail.component.ts:75]: Just noticed that we have a done attribute. If used correctly is should be exactly the information that I require.

```json
[{
    "submissionTime": 1605484800000,
    "done": false,
    "id": 19198,
    "results": []
}]
```

Comment (andrej-sajenko) [reply web-gui/src/app/page-components/task-detail/task-detail.component.ts]: I have tried to submit the sql result `SELECT 1;` for the only existing task on the test server.
Waited about 15 Min without results. This is quite nice to test this feature, but does it suppose to work like this?

Comment (mxsph) [reply web-gui/src/app/page-components/task-detail/task-detail.component.ts]: yes, this is because no Cheker configuration was defined there.

**Review by mxsph — COMMENTED** [review]
Now everything works, but the text under "Last submission:" will not be updated after receiving the result (there is still the message of the last submission)

**Comment by hwng38** [comment]
The table is still missing, but I could make another pull request after this one?

**Comment by andrej-sajenko** [comment]
@mxsph There is something strange going on. The test server is using the current version of the dev branch. Using the test server I can not even create a configuration without getting a 400 error.

**Comment by andrej-sajenko** [comment]
> The table is still missing, but I could make another pull request after this one?

Sure, you can even make it before this one is accepted.

**Review by hwng38 — APPROVED** [review]

**Comment by andrej-sajenko** [comment]
> Updating the solution works, but the loading circle is not displayed while waiting for the submission result (it is only displayed when you exit and reopen the task).

I have found and fixed the problem. It was a reference error, i.e., a reference to submissions.result was used but only submissions was was replaced by a new object after update.

**Review by mxsph — APPROVED** [review]
:+1:
