### PR TITLE
Correct sorting order for course participant roles

### LINKED ISSUE #593: Users cannot be sorted by roles
When trying to sort users by role this does not work.

Peek 2021-12-03 16-38

### PR DESCRIPTION
**Pull request by Zitrone44**
Closes #593

### CODE REVIEW

File: web-gui/src/app/tool-components/participants/participants.component.ts [hunk 1]
```diff
@@ -58,6 +58,21 @@ export class ParticipantsComponent implements OnInit {
...
+          if (field === 'globalRole') {
+            const role = this.getRole(user.id);
+            switch (role) {
+              case 'STUDENT': return 0;
+              case 'TUTOR': return 1;
+              case 'DOCENT': return 2;
+              default:
+                console.error(`unknown role: ${role}`);
+                return -1;
+            }
```
Comment (mxsph) [inline web-gui/src/app/tool-components/participants/participants.component.ts:71]: I would move this code to `model/Roles.ts`, so that you get the value with `Roles.CourseRole.getSortOrder` (Same as `isDocent`).

**Review by mxsph — CHANGES_REQUESTED** [review]
Looks good so far, I only noticed two things:

- [ ] In the Global User Overview the roles are sorted the other way around, I would adjust that.

**Review by mxsph — APPROVED** [review]
