### PR TITLE
After changing the task Media type, the validation will not be reset

### LINKED ISSUE #786: After changing the task Media type, the validation will not be reset
**Describe the bug**

When creating a task, if you set the media type to 'Calculation' and then back to 'Text', it is no longer possible to create the task because the validation still tries to validate the fields of the calculation media type.

**To Reproduce**
1. Create a Task
2. Select the Media Type `Berechnung`
3. Select the Media Type `Text`

**Expected behavior**
Even after changing the media type, it should be possible to create a task.

**Screenshots**
error

### PR DESCRIPTION
**Pull request by nicosoethe**
resolves #786

### CODE REVIEW

File: modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts [hunk 1]
```diff
@@ -43,12 +43,12 @@ export class TaskNewDialogComponent implements OnInit {
...
     mediaType: new UntypedFormControl(defaultMediaType),
     requirementType: new UntypedFormControl(defaultrequirement),
-    exelFile: new UntypedFormControl(""),
-    userIDField: new UntypedFormControl(""),
-    inputFields: new UntypedFormControl(""),
-    outputFields: new UntypedFormControl(""),
+    exelFile: new UntypedFormControl(""), //val
+    userIDField: new UntypedFormControl(""), //val
+    inputFields: new UntypedFormControl(""), // val
+    outputFields: new UntypedFormControl(""), //val
```
Comment (TimonPllkrn) [inline modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts:49]:
```suggestion
    exelFile: new UntypedFormControl(""),
    userIDField: new UntypedFormControl(""),
    inputFields: new UntypedFormControl(""),
    outputFields: new UntypedFormControl(""),
```

File: modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts [hunk 2]
```diff
@@ -43,12 +43,12 @@ export class TaskNewDialogComponent implements OnInit {
...
     pointFields: new UntypedFormControl(""),
-    decimals: new UntypedFormControl(2),
+    decimals: new UntypedFormControl(2), //val
```
Comment (TimonPllkrn) [inline modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts:51]:
```suggestion
    decimals: new UntypedFormControl(2),
```

**Review by TimonPllkrn — CHANGES_REQUESTED** [review]

**Review by TimonPllkrn — CHANGES_REQUESTED** [review]
