### PR TITLE
Course result query

### LINKED ISSUE #526: Course result Error
If a course has too many tasks/Submissions, an error is thrown when querying the course results: 

```
Out of sort memory, consider increasing server sort buffer size; 
nested exception is java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size
```

To fix this error, this SQL query should be improved:

```sql
SELECT user_id, prename, surname, email, username, global_role, alias, 
	JSON_ARRAYAGG(JSON_OBJECT("task", JSON_OBJECT("id", task_id,
							 "name", name, 
                             "deadline", deadline, 
                             "media_type", media_type, 
                             "description", description), 
                             "attempts", attempts, 
                             "passed", passed)) as results,
    (count(CASE WHEN passed >= 1 THEN 1 END) = count(task_id)) as "passed"
	from (SELECT *, count(CASE WHEN passed_checker >= 1 THEN 1 END) as passed from (SELECT *, count(DISTINCT submission_id) as "attempts", count(CASE WHEN exit_code = 0 THEN 1 END) = count(Distinct configuration_id) as "passed_checker"
    from user
    LEFT JOIN user_course using (user_id)
    JOIN task using (course_id)
    LEFT JOIN user_task_submission using (user_id, task_id)
	LEFT join checkrunner_configuration using (task_id) 
	LEFT JOIN checker_result using (submission_id, configuration_id) 
    where course_id = 161 group by user_id, task_id, submission_id order by user_id, task_id) results_by_submission
    group by user_id, task_id
    ) results 
    group by user_id;
```
(This query is in this file: https://github.com/thm-mni-ii/feedbacksystem/blob/6af396213e2a15b940fa1d8f019cf1d5b0277fb1/ws/src/main/scala/de/thm/ii/fbs/services/persistance/CourseResultService.scala)

It would also be possible to increase the `sort memory` but the default value is `2MB` and only from a value of `40MB` the query would work for the course where the error occurred (so this is also not a practical solution).

### PR DESCRIPTION
**Pull request by snicki13**
Fixes #526 and typo in package "persistence"

### CODE REVIEW

**Comment by snicki13** [comment]
Sorry, I tried to amend the last change, but it obviously did not work.

**Review by mxsph — CHANGES_REQUESTED** [review]
Looks good so far :+1: 

I only noticed a few errors:

- The tasks in the course results should be sorted in ascending order by `task_id` (otherwise they will be displayed incorrectly in the Frontend).
- The Course Evaluation Routes don't work anymore (I fixed them already)

File: ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseResultService.scala [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+    |                     left join checkrunner_configuration cc using (task_id)
+    |                     left join checker_result cr using (submission_id, configuration_id)
+    |            group by uts.user_id, uts.task_id
+    |) as submissions using (user_id, task_id)
+    |where course_id = ?
+    |group by u.user_id;
+    |""".stripMargin, (res, _) => parseResult(res), cid)
+
+  private def parseResult(res: ResultSet): CourseResult = CourseResult(
+    courseRegistration.parseUserResult(res), res.getBoolean("passed"), objectMapper.readValue(res.getString("results"), classOf[Array[TaskResult]]).toList
```
Comment (mxsph) [inline ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseResultService.scala:64]: I had to change `List` to `Array` because otherwise the following error would occur when using the object in Scala (e.g. in `/api/v1/courses/:id/evaluation/results`): 

```
java.lang.ClassCastException: class scala.collection.immutable.HashMap cannot be cast to class de.thm.ii.fbs.model.Task (scala.collection.immutable.HashMap and de.thm.ii.fbs.model.Task are in unnamed module of loader 'app')


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.parseTasksResult(EvaluationContainerService.scala:137) ~[ws-1.0-SNAPSHOT.jar:na]


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.parseResult(EvaluationContainerService.scala:127) ~[ws-1.0-SNAPSHOT.jar:na]


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.$anonfun$getOne$1(EvaluationContainerService.scala:52) ~[ws-1.0-SNAPSHOT.jar:na]


	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:768) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at de.thm.ii.fbs.util.DB$.query(DB.scala:32) ~[ws-1.0-SNAPSHOT.jar:na]


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.getOne(EvaluationContainerService.scala:46) ~[ws-1.0-SNAPSHOT.jar:na]


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.$anonfun$createContainer$2(EvaluationContainerService.scala:93) ~[ws-1.0-SNAPSHOT.jar:na]


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.$anonfun$createContainer$2$adapted(EvaluationContainerService.scala:93) ~[ws-1.0-SNAPSHOT.jar:na]


	at scala.Option.flatMap(Option.scala:283) ~[scala-library-2.13.1.jar:na]


	at de.thm.ii.fbs.services.persistence.EvaluationContainerService.createContainer(EvaluationContainerService.scala:93) ~[ws-1.0-SNAPSHOT.jar:na]


	at de.thm.ii.fbs.controller.CourseEvaluationController.createContainer(CourseEvaluationController.scala:103) ~[ws-1.0-SNAPSHOT.jar:na]


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]


	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]


	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]


	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]


	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.jasig.cas.client.util.AssertionThreadLocalFilter.doFilter(AssertionThreadLocalFilter.java:50) ~[cas-client-core-3.5.1.jar:3.5.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:71) ~[cas-client-core-3.5.1.jar:3.5.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

If you know a better solution for this problem, you are welcome to adapt it :smile:

**Comment by snicki13** [comment]
Did you encounter the above exception before changing the ObjectMapper to Autowired and only in the EvaluationContainerService?
Jackson needs to have an extra Module registered to handle Scala Collections like List. If the module is not registered it will fail with the above Exception. When Autowired, the created bean should have the needed Module registered by default, which is why it worked with list in the CourseResultService.

I will check it again, if it somehow does not work, I will configure a custom bean for future usage.

**Comment by snicki13** [comment]
I will check on it later and add the order by to the query.

**Comment by mxsph** [comment]
> Did you encounter the above exception before changing the ObjectMapper to Autowired and only in the EvaluationContainerService?
> Jackson needs to have an extra Module registered to handle Scala Collections like List. If the module is not registered it will fail with the above Exception. When Autowired, the created bean should have the needed Module registered by default, which is why it worked with list in the CourseResultService.

I encountered the above exception before and after changing the ObjectMapper to Autowired in both services (`EvaluationContainerService`, `CourseResulstService`). 


> I will check it again, if it somehow does not work, I will configure a custom bean for future usage.

:+1:

**Comment by snicki13** [comment]
I checked it again. Works like a charm with scala list and autowired objectMapper. 
Tested in IDE and Docker.
I did not touch the EvaluationContainerService though, because I don't know how to test it yet.

**Comment by mxsph** [comment]
> I checked it again. Works like a charm with scala list and autowired objectMapper.
> Tested in IDE and Docker.
> I did not touch the EvaluationContainerService though, because I don't know how to test it yet.

yes, for the Course Result Service (`/api/v1/courses/156/results`) this works without problems, but if you send a request to `/api/v1/courses/156/evaluation/results` you will get the error message described in https://github.com/thm-mni-ii/feedbacksystem/pull/531#discussion_r610832948. As far as I can see, the object generated by the objectMapper is not a real list. Since in the `Course Result Service` this is no longer used (but only converted to JSON) this is not a problem there, but if you use this in Scala so that it has to be a list, it fails.

> I will check on it later and add the order by to the query.

Sorting does not yet work correctly in courses with many users/assignments/deliverables (See the course 'CS1020 Database Systems' on the live system).

**Comment by snicki13** [comment]
Order by in the SQL-Query has no impact on the JSON_ARRAYAGG Method, so it has to be sorted in-memory in Scala. To achieve this smoothely TaskResult now extends the Ordered trait and is given a natural order by its nested Task.id and the List of TaskResult is then sorted.

**Review by mxsph — CHANGES_REQUESTED** [review]
The sequence of tasks and the `Course Evaluation API` now works :+1: 

However, I noticed another error in the results:

If you have a task that has two (or more) checkers and one passes and the other doesn't, it will show up as passed in the results view even though the task didn't pass:

error

**Comment by snicki13** [comment]
Sorry, I fixed the double checked tasks a while ago and did not push it...

**Review by mxsph — CHANGES_REQUESTED** [review]
With this bug fix, you have unfortunately broken the calculation of whether the task has been passed or not: If you have a task where there are several submissions, some of which have failed (or not passed), it is displayed as not passed even though they have been passed.

**Review by mxsph — APPROVED** [review]
Now everything works :tada:
