### PR TITLE
Fix editing task check configurations

### LINKED ISSUE #766: Editing task check configurations does not work
**Describe the bug**
If you try to edit a task check configuration, a new empty check configuration is added (see gif). Furthermore, when editing the configuration, the old values are not pre-filled and you have to select everything again.

**To Reproduce**
1. Create a Task
2. Add a check configuration
3. edit the check configuration

**Expected behavior**
When editing task review configurations, no new configuration should be created and the old values should be pre-filled.

**Screenshots**
error

### PR DESCRIPTION
**Pull request by Medienkunzt**
There are still some issues with the validation of the files.
To close this topic for the time being, I have created another issue. See: #825

resolves #766

### CODE REVIEW

File: modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts [hunk 1]
```diff
@@ -58,10 +62,46 @@ export class NewCheckerDialogComponent implements OnInit {
...
     }
-    this.courseId = this.data.courseId;
-    this.taskId = this.data.taskId;
-    this.setDefaultValues();
-    this.choosedSQLChecker = false;
+
+    if (this.checker.mainFileUploaded == true) {
+      this.checkerService
+        .getChecker(this.courseId, this.taskId)
+        .pipe(map((checkers) => checkers[0]))
```
Comment (TimonPllkrn) [inline modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts:69]: Here the main file is loaded only for the first checker. With several checkers, the content of the main file of the first checker is always returned. Although you can't download this at the moment, I would still adapt it.

File: modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts [hunk 2]
```diff
@@ -58,10 +62,46 @@ export class NewCheckerDialogComponent implements OnInit {
...
+            .fetchSecondaryFile(this.courseId, this.taskId, checker.id)
+            .subscribe((secondaryFileBlob) => {
+              this.secondaryFile[0] = new File(
+                [secondaryFileBlob],
+                "secondaryFile"
+              );
+              this.fileCounter++;
+            });
+        });
+    }
```
Comment (TimonPllkrn) [inline modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts:95]: These two if conditions have the same content except for the method call. I would suggest instead of the `fetchMainFile` and the `fetchSecondaryFile` methods to write a `fetchFile` method with parameter, thereby the code duplicates of the methods `fetchMainFile`, `fetchSecondaryFile`, `getMainFile`, `getSecondaryFile` would be omitted and it would be more generic for the future. In addition, the If statement  would then only affect the parameter and also the code duplication here would be omitted.

**Review by TimonPllkrn — CHANGES_REQUESTED** [review]

File: modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts (hunk 1 above)
Comment (Medienkunzt) [reply modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts]: generic optioan applied

File: modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts (hunk 2 above)
Comment (Medienkunzt) [reply modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts]: refactoring of the fetchFile/getFile method

**Review by mxsph — APPROVED** [review]
