### PR TITLE
The Excel shows an error for some of the deliveries although they are actually correct

### LINKED ISSUE #757: The Excel shows an error for some of the deliveries although they are actually correct
**Describe the bug**
The Excel shows an error for some of the deliveries although they are actually correct. After further testing, it turned out that the data type of the cells that are written when changing is wrong, which causes the `+` operations to add strings and not the numbers.

**Expected behavior**
The Excel-Checker should accept all correct solutions

### PR DESCRIPTION
**Pull request by mxsph**
resolves #757

### CODE REVIEW

File: modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala [hunk 1]
```diff
@@ -71,7 +71,10 @@ class ExcelService {
   private def setCells(workbook: XSSFWorkbook, changeFields: List[ExcelMediaInformationChange]): Unit = {
     changeFields.foreach(f => {
       val sheet = workbook.getSheetAt(f.sheetIdx)
-      this.getCell(sheet, f.cell).setCellValue(f.newValue)
+      f.newValue.toDoubleOption match {
+        case Some(v) => this.getCell(sheet, f.cell).setCellValue(v)
+        case _ => this.getCell(sheet, f.cell).setCellValue(f.newValue)
+      }
```
Comment (Zitrone44) [inline modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala:77]:
```suggestion
      val newValue = f.newValue.toDoubleOption match {
        case Some(v) => v
        case _ => f.newValue
      }
      this.getCell(sheet, f.cell).setCellValue(newValue)
```

**Review by Zitrone44 — CHANGES_REQUESTED** [review]
Works well :+1:

But i have a small code improvement suggestion.

File: modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala (hunk 1 above)
Comment (mxsph) [reply modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala:77]: This suggestion does not work since it results in a compile error: `Cannot resolve overloaded method 'setCellValue'`.

**Review by Zitrone44 — APPROVED** [review]
